### ISSUE TITLE
Style website

### ISSUE THREAD

**Issue by watrall** [chi-initiative/kora-documentation#41]
Sidebar header: #007C83

Insert Kora logo (in white) in sidebar header - like https://docs.readthedocs.io/en/stable/webhooks.html

Sidebar background color: #283C46

submenu sidebar background color: #F5F6F7

submenu sidebar section header: keep as is (white) 

Body link color: #04B6AF

Body text color: #283C46

Sidebar section header: #ffffff (Add some space above these headers if possible - 20px of margin-top looks good.)

Sidebar submenu links (Hover)  - background color: #DAE0E3, color: #283C46 ((have the text color be this for non hovered as well - instead of the grey)

Sidebar Active Submenu Drawer Title - Hover
Remove the hover effect so the title of the drawer doesn’t change to white on hover.

Some of the sidebar links have an active state that change the color to red on click for a split second. I would say to just remove these if possible.

Please document (here) the files (including locations) and associated classes/elements where these changes are made.

**Comment by watrall** [comment]
when you are doing this, we need to be mindful that updating the mkdocs install won't wipe out any custom styling.

**Comment by watrall** [comment]
This style should also be applied to mobile

**Comment by geyerbri** [comment]
Changes implemented affect desktop version (have not yet checked mobile).

All changes are found in [extra.css](../blob/master/docs/css/extra.css), which should continue to override the theme as it is updated. Given that this last major update brought readthedocs in line with sphinx, it's unlikely major changes to the navbar structure will again occur (this is in reference to changing the coding of navbar category titles from no-anchor list items to standalone paragraphs). See mkdocs/mkdocs#2045.

Body text color is `.wy-nav-content`. Body link color is `.wy-nav-content a` (and variations for `:hover`, `:visited`, etc). 

Sidebar header is `.wy-side-nav-search`. Header icon is `.fa-home::before .icon-home::before` and defined as `content: url(...)`. 

Main-level for the sidebar is `.wy-nav-side`. The font color has been set to white, but if off-white is desired instead, `#D9D9D9` looks fine.

Hovering on main-level is `.wy-menu-vertical a:hover, .wy-menu-vertical a:active`.

First submenu level is `.wy-menu-vertical ul li`. For hover and current of second submenu (the colors are set to be the same), `.wy-menu-vertical li.toctree-l1.current a:hover, .wy-menu-vertical li.toctree-l2.current>a`.

Second submenu level is `.wy-menu-vertical li.toctree-l2.current li.toctree-l3>a`. For hovering and the current of third submenu (again, same color), `.wy-menu-vertical li.toctree-l2.current a:hover,
.wy-menu-vertical li.toctree-l3.current>a`.

Categories/section headings (which aren't links) are `.wy-menu-vertical header, .wy-menu-vertical p.caption`. The "Home" link is specifically `.wy-menu-vertical li.toctree-l1 a[href="../.."], .wy-menu-vertical li.toctree-l1 a[href="./."], .wy-menu-vertical li.toctree-l1 a[href="../"], .wy-menu-vertical li.toctree-l1.current a[href="."]` (it doesn't have an ID). These are known because they're needed for the indenting.

All of this is also laid out in [the file](../blob/master/docs/css/extra.css) with comments.

**Comment by watrall** [comment]
Totally forgot to give you the Kora logo file.  This should completely replace the current header (logo + Kora 3 documentation).  As an aside, we've made the decision that the software is just called "Kora" (as opposed to Kora 3), while the version will be 3 when referenced in any documentation.  
![kora_logo](https://user-images.githubusercontent.com/109138/83026956-782d5300-9ffd-11ea-81b8-19cd2694d3b9.png)

**Comment by watrall** [comment]
well, thats hilarious.  logo is included in previous comment...but because its while on transparent, you can't see it.

**Comment by geyerbri** [comment]
Apologies, I should not have closed this with that comment! That's what I get for writing something up at the end of my day...

**Comment by watrall** [comment]
hi-res logo file

![KoraLogo-White](https://user-images.githubusercontent.com/109138/83176767-05e76c00-a0ec-11ea-87a2-a03a1c8b66d7.png)

**Comment by geyerbri** [comment]
Updated description of classes/elements used in extra.css to make adjustments:

Body text color is `.wy-nav-content`. Body link color is `.wy-nav-content a` (and variations for `:hover`, `:visited`, etc). 

Sidebar header is `.wy-side-nav-search`. Header icon is `.icon.icon-home` and defined as `content: url(...)`. 

Main-level background for the sidebar is `.wy-nav-side`. 

Mobile top navbar is `.wy-nav-top`

In mobile, Kora icon added before site name via `.wy-nav-top a::before`. Note, to control size and spacing, this is done as a `background-image`.

Sidebar fonts is controlled by `.wy-menu-vertical a`.

Hovering on main-level is `.wy-menu-vertical a:hover, .wy-menu-vertical a:active`.

First submenu level is `.wy-menu-vertical ul li`. For hover of first and current of second submenu (the colors are set to be the same), `.wy-menu-vertical li.toctree-l1.current a:hover, .wy-menu-vertical li.toctree-l2.current>a`.

Second submenu level is `.wy-menu-vertical li.toctree-l2.current li.toctree-l3>a`. For hover of second and the current of third submenu (again, same color), `.wy-menu-vertical li.toctree-l2.current a:hover, .wy-menu-vertical li.toctree-l3.current>a`.

Categories/section headings (which aren't links) are `.wy-menu-vertical header, .wy-menu-vertical p.caption`. Top-level pages - same level as categories - is specifically `.wy-menu-vertical li.toctree-l1:only-child a`. This controls indenting as well.

All of this is also laid out in [the file](../blob/master/docs/css/extra.css) with comments.
